[다미] proposal-object-rest-spread 번역
11st-corp/tc39-ko pull request #22
Opened 2023-03-29 13:48 UTC by damilog

proposal-object-rest-spread 번역 입니다.

2023-05-04 05:54 UTC, hochan222 requested changes
고생 많으셨습니다.

세부 리뷰 사항 하기에 남겨두었습니다. 많이 배워갑니다!!

2023-05-04 05:54 UTC, hochan222 commented on glossary.md
> +| initializer | 초기화 구문 | |
```suggestion
| initializer | 초기화 구문 | |
```

경우에 따라서 "구문"이 붙어서 어색한 경우가 생길 수 있을듯합니다. initializer는 초기화 까지만 적어두는건 어떨까요? 아니면 제거해도 좋을듯합니다.

2023-05-04 05:54 UTC, hochan222 commented on glossary.md
> +| merge | 합병 | |
공통 용어인데 너무 세세하게 제한을 두는것 같아요. 본문은 작성자가 자유롭게 번역하도록 정말 필요한 단어 아니면 적지 않는것이 좋아 보여서 리뷰드렸습니다.

2023-05-04 05:54 UTC, hochan222 commented on src/ko/proposal-async-await.md
> +# Async Functions for ECMAScript
다른 PR과 파일이 중복된듯 합니다.

2023-05-04 05:54 UTC, hochan222 commented on src/ko/proposal-object-rest-spread.md
> +ECMAScript 6은 배열 구조 분해 할당을 위한 [나머지 요소](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)와 배열 리터럴을 위한 [전개 요소](https://developer.mozilla.org/en-US/do
전개 요소 👍👍

2023-05-04 05:54 UTC, hochan222 commented on src/ko/proposal-object-rest-spread.md
> +## [명세](https://tc39.es/proposal-object-rest-spread/)
```suggestion
## [명세서](https://tc39.es/proposal-object-rest-spread/)
```

<img width="470" alt="image" src="https://user-images.githubusercontent.com/22424891/236121241-af86c742-97b6-4740-a7a8-98ed565bab99.png">

2023-05-04 05:54 UTC, hochan222 commented on src/ko/proposal-object-rest-spread.md
> +객체 초기자의 전개 속성 제공된 객체에서 새로 생성된 객체로 자체 열거 가능한 속성을 복사합니다.
```suggestion
객체 초기자의 전개 속성은 제공된 객체에서 새로 생성된 객체로 자체 열거 가능한 속성을 복사합니다.
```

2023-05-08 15:12 UTC, chanuuuuu approved these changes
고생하셨습니다:)

2023-05-10 09:27 UTC, damilog commented
@hochan222 , @chanuuuuu 님 [리뷰 반영](https://github.com/11st-corp/tc39-ko/pull/22/commits/69cf00a8a5658efa59051af313a7d285e3f15674)했습니다 감사합니다 👍

2023-05-12 04:36 UTC, hochan222 approved these changes
LGTM :)

2023-05-12 04:36 UTC, merged