[다미] Optional catch binding
11st-corp/tc39-ko pull request #24
Opened 2023-04-06 14:43 UTC by damilog

Optional catch binding 제출합니다.

2023-05-03 13:43 UTC, huckjoo approved these changes
고생하셨습니다 😄

2023-05-04 05:38 UTC, hochan222 requested changes
고생 많으셨습니다! 

몇가지 리뷰사항 하기에 남겨두었습니다 :)

2023-05-04 05:38 UTC, hochan222 commented on src/ko/proposal-async-await.md
> +이 제안은 `async`와 `await`를 포함한 ES5 코드를 컴파일하고 기존 브라우저와 런타임에서 실행될 바닐라 ES5 까지 기다릴 수 있는 [regenerator](https://github.com/facebook/regenerator)에서 구현됩니다.
```suggestion
본 제안은 `async`와 `await`를 포함한 ES5 코드를 컴파일하고 기존 브라우저와 런타임에서 실행될 바닐라 ES5 까지 기다릴 수 있는 [regenerator](https://github.com/facebook/regenerator)에서 구현됩니다.
```

다미님께서 <https://github.com/11st-corp/tc39-ko/pull/23#discussion_r1183815840> 에서 같은 리뷰를 주셨기에 리뷰 드렸습니다!

2023-05-04 05:38 UTC, hochan222 commented on src/ko/proposal-async-await.md
> +```js
```suggestion
```sh
```

2023-05-04 05:38 UTC, hochan222 commented on src/ko/proposal-optional-catch-binding.md
> +본 제안은 ECMA스크립트에 문법적인 변경을 가하여 바인딩을 사용하지 않을 경우 캐치 바인딩을 생략할 수 있도록 합니다. 이는 다음과 같은 패턴에서 자주 발생합니다.
```suggestion
본 제안은 ECMAScript에 문법적인 변경을 가하여 바인딩을 사용하지 않을 경우 캐치 바인딩을 생략할 수 있도록 합니다. 이는 다음과 같은 패턴에서 자주 발생합니다.
```

상표는 번역하지 않는것이 좋습니다.

2023-05-04 05:40 UTC, damilog commented on src/ko/proposal-async-await.md
> +이 제안은 `async`와 `await`를 포함한 ES5 코드를 컴파일하고 기존 브라우저와 런타임에서 실행될 바닐라 ES5 까지 기다릴 수 있는 [regenerator](https://github.com/facebook/regenerator)에서 구현됩니다.
오 감사해요!!

2023-05-04 05:44 UTC, hochan222 commented on src/ko/proposal-async-await.md
> +ECMAScript에 Promise 및 Generators의 도입은 ECMAScript에서 비동기 코드를 작성하기 위한 언어 수준 모델을 획기적으로 개선할 수 있는 기회를 제공합니다. 이 명세는 [여기](https://tc39.es/proposal-async-await/)에서 확인할 수 있습니다.
```suggestion
ECMAScript에 Promise 및 Generators의 도입은 ECMAScript에서 비동기 코드를 작성하기 위한 언어 수준 모델을 획기적으로 개선할 수 있는 기회를 제공합니다. 이 명세는 [여기](https://tc39.es/proposal-async-await/)에서 확인할 수 있습니다.
```
(1) Promise, Generators를 프로미스, 제네레이터로 번역하는건 어떤가요..? 단순 의견

2023-05-08 15:18 UTC, chanuuuuu commented on src/ko/proposal-async-await.md
> +ECMAScript에 Promise 및 Generators의 도입은 ECMAScript에서 비동기 코드를 작성하기 위한 언어 수준 모델을 획기적으로 개선할 수 있는 기회를 제공합니다. 이 명세는 [여기](https://tc39.es/proposal-async-await/)에서 확인할 수 있습니다.
일단 저의 의견은 단어를 그대로 사용해야하지 않을까 생각합니다. 아무래도 한글로 명사를 번역하게 되면, 다른 표현과 혼동될 수 있다고 생각합니다.

2023-05-08 15:19 UTC, chanuuuuu approved these changes

2023-05-08 15:19 UTC, chanuuuuu commented on src/summary/proposal-async-await.md
> +[Task.js](https://taskjs.org) 및 유사한 라이브러리는 generator를 사용하여 동일한 의미를 유지하는 코드를 더욱 단순화하는 방법을 제공합니다. :
```suggestion
[Task.js](https://taskjs.org) 및 유사한 라이브러리는 generator를 사용하여 동일한 의미를 유지하는 코드를 더욱 단순화하는 방법을 제공합니다.
```

2023-05-08 15:19 UTC, chanuuuuu commented on src/summary/proposal-async-await.md
> +이미 Promise가 있는 코드는 이러한 종류의 루프 및 예외 처리가 어려운 직선 콜백 스타일에서 훨씬 개선되었습니다.
```suggestion
이미 Promise가 있는 코드는 이러한 종류의 루프 및 예외 처리가 어려운 선형 콜백 스타일에서 훨씬 개선되었습니다.
```
연속된 의미를 가지는 '선형'이라는 단어가 어울릴 것 같아서 의견 올립니다:)

2023-05-08 15:19 UTC, chanuuuuu approved these changes

2023-05-10 09:40 UTC, damilog commented
@hochan222 님 [리뷰 반영](https://github.com/11st-corp/tc39-ko/pull/24/commits/1a74b61bbbffafbabaaee7d0463f1753b6711188) 했습니다 확인 후 approve 부탁드려요~

2023-05-10 09:43 UTC, damilog commented on src/ko/proposal-async-await.md
> +ECMAScript에 Promise 및 Generators의 도입은 ECMAScript에서 비동기 코드를 작성하기 위한 언어 수준 모델을 획기적으로 개선할 수 있는 기회를 제공합니다. 이 명세는 [여기](https://tc39.es/proposal-async-await/)에서 확인할 수 있습니다.
@chanuuuuu 님 의견 감사합니다~! 관련 지난 스터디 때 관련 논의가 있었는데요. 번역되어 통용되는 기술 용어는 되도록 한글로 번역하는 것으로 정해진 점 참고 부탁드립니다. (자세한 내용은 슬랙에서..)

단어 번역시
generator -> 제너레이터
promise -> 프로미스 
단어장에 어떻게 번역할지 표기해놓기

2023-05-12 04:37 UTC, hochan222 approved these changes
LGTM :)

2023-05-12 06:55 UTC, merged