[혁주] Asynchronous Iterators for JavaScript 번역
11st-corp/tc39-ko pull request #25
Opened 2023-04-06 15:26 UTC by huckjoo

2023-05-03 14:59 UTC, damilog approved these changes
고생하셨습니다 🙂

2023-05-03 14:59 UTC, damilog commented on src/ko/asynchronous-iterators.md
> +```jsx
js가 알맞아 보입니다!

2023-05-03 14:59 UTC, damilog commented on src/ko/asynchronous-iterators.md
> +- 호출되면, 비동기 제너레이터 함수는 객체를 반환합니다. (`next`, `throw`, 그리고 `return`) 메서드를 가진 비동기 제너레이터는 `{value, done}`을 직접적으로 반환하는 대신, `{value, done}`을 위한 promise를 반환합니다. 이것은 반환된 비동기 제너레이터 객체를 비동기 반복자로 자동으로 만들어줍니다.
generator는 제너레이터로 번역하였으니 promise도 프로미스로 번역하는게 어떨까요? 
만일 `Promise` 객체를 의미하고자 한다면 대문자 P로 시작하는 게 좋을 것 같습니다.
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise

2023-05-03 14:59 UTC, damilog commented on src/ko/asynchronous-iterators.md
> +### Native implementations
음..네이티브 구현은 어떨까요?🤔

2023-05-03 14:59 UTC, damilog commented on src/ko/proposal-trailing-function-commas.md
> +버전제어 시스템(git, subversion, mercurial 등)이 관리하는 코드에서 이런 변경이 일어날 때 3번째 줄과 9번째 줄에 대한 blame/annotation 코드 기록 정보가 쉼표를 추가한 사람(기존에 매개변수를 추가한 사람이 아닌)을 가리키도록 업데이트됩니다.
`버전 제어`

2023-05-04 05:28 UTC, hochan222 requested changes
고생 많으셨습니다!! 

몇가지 리뷰 사항 남겨두었습니다. 중복되는 리뷰는 최초 한개만 남겨두었습니다.

많은 것 배워갑니다!

2023-05-04 05:28 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +우리는 비동기 객체에 대해 반복되는 for-of 반복문의 변형을 소개합니다. 사용 예시는 다음과 같습니다.
```suggestion
우리는 비동기 객체에 대해 반복되는 `for-of` 반복문의 변형을 소개합니다. 사용 예시는 다음과 같습니다.
```

2023-05-04 05:28 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +비동기 for-of 문은 비동기 함수 및 비동기 제너레이터 함수 내에서만 허용됩니다(아래 문서 참조).
```suggestion
비동기 for-of 문은 비동기 함수 및 비동기 제너레이터 함수 내에서만 허용됩니다(후자는 아래 문서 참조).
```

> (see below for the latter).

latter가 누락되었습니다.

2023-05-04 05:28 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +시퀀스의 다음 value에 접근할 때마다, 우리는 암묵적으로 promise의 반환을 `await` 합니다.
```suggestion
시퀀스의 다음 값에 접근할 때마다, 우리는 암묵적으로 프로미스의 반환을 `await` 합니다.
```

(1) promise 는 조그마한 의견입니다. (사실 프라미스가 맞는 표기이지만, 대다수 관례를 따라갑니다.)

2023-05-04 05:28 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +## 비동기 제너레이터 함수
해당 제목만 번역하신 이유가 있을까요?

2023-05-04 05:28 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +- 호출되면, 비동기 제너레이터 함수는 객체를 반환합니다. (`next`, `throw`, 그리고 `return`) 메서드를 가진 비동기 제너레이터는 `{value, done}`을 직접적으로 반환하는 대신, `{value, done}`을 위한 promise를 반환합니다. 이것은 반환된 비동기 제너레이터 객체를 비동기 반복자로 자동으로 만들어줍니다.
```suggestion
- 호출될 때, 비동기 제너레이터 함수는 `{value, done}`을 직접적으로 반환하는 대신, `{value, done}`에 대한 프라미스를 반환하는 메서드(`next`, `throw`, 그리고 `return`)를 반환하는 비동기 제너레이터인 객체를 반환합니다. 이것은 반환된 비동기 제너레이터 객체를 비동기 반복자로 자동으로 만들어줍니다.
```

2023-05-04 05:28 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +이 함수는 비동기 제너레이터 객체를 반환합니다. 이 객체는 이전 예제에 나와있는 것처럼 `for`-`await`-`of` 구문과 함께 사용할 수 있습니다.
```suggestion
그런 다음 이 함수는 앞의 예제와 같이 `for`-`await`-`of`와 함께 사용할 수 있는 비동기 제너레이터 객체를 반환합니다.
```
음.. 짧게 번역할 수 있을것같아 리뷰드렸습니다. 관계 대명사를 끊지말고 하나로 이어보는건 어떨까요?

2023-05-04 05:28 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +# Asynchronous Iterators for JavaScript 번역
```suggestion
# Asynchronous Iterators for JavaScript
```

다른 문서에서는 번역이 안붙어있어서 붙인다면 혁주님의 다른 문서에도 붙이는것이 좋아보입니다!

2023-05-04 05:28 UTC, hochan222 commented on src/ko/proposal-trailing-function-commas.md
> +이러한 경우 다른 코드 기여자가 나타나서 이러한 매개 변수 목록 중 하나에 다른 매개 변수를 추가하면 다음과 같이 두 개의 줄을 업데이트 해야 합니다.
```suggestion
이러한 경우 다른 코드 기여자가 나타나서 이러한 매개 변수 목록 중 하나에 다른 매개 변수를 추가하면 다음과 같이 두 개의 줄을 갱신해야 합니다.
```

update를 갱신으로 번역하는건 어떤가요?

2023-05-04 05:28 UTC, hochan222 commented on src/ko/proposal-trailing-function-commas.md
> +이 문제를 완화하기 위해, 몇몇 다른 언어들(Python, D, Hack, …다른 언어들)은 매개 변수 목록에서 trailing comma를 허용하는 문법 지원을 추가하였습니다. 이는 코드 기여자들이 줄별 매개 변수 목록에서 항상 매개변수 추가의 끝에 trailing comma를 포함할 수 있게 하여 코드 기여 문제에 대해 다시는 고민할 필요가 없도록 했
```suggestion
이 문제를 완화하기 위해, 몇몇 다른 언어들(Python, D, Hack, …다른 언어들)은 매개 변수 목록에서 후행 쉼표(trailing comma)를 허용하는 문법 지원을 추가하였습니다. 이는 코드 기여자들이 줄별 매개 변수 목록에서 항상 매개변수 추가의 끝에 후행 쉼표를 포함할 수 있게 하여 코드 기여 문제에 대해 다시는 고민할 필요가 없도록 했습니다.
```

처음만 표시해도 충분할듯합니다. 혹은 "후행 쉼표"만 작성해도 좋을듯합니다.

2023-05-04 05:28 UTC, hochan222 commented on src/ko/proposal-trailing-function-commas.md
> +본 저장소에는 제안서 슬라이드, 매개 변수 목록에서 trailing comma를 허용하기 위해 해킹된(hacked) esprima<sup>[1][]</sup> 버전, 빌드 단계에서 trailing comma를 ES5-compatible non-trailing comma로 변환하는 것이 가능하다는 것을 보여주는 매우 간단한 CLI 유틸리티가 포함되어 있습니
```suggestion
본 저장소에는 제안서 슬라이드, 매개 변수 목록에서 후행 쉼표를 허용하기 위해 해킹된(hacked) esprima<sup>[1][]</sup> 버전, 빌드 단계에서 후행 쉼표를 ES5 호환 비후행 쉼표로 쉽게 변환하는 것이 가능하다는 것을 보여주는 매우 간단한 CLI 유틸리티가 포함되어 있습니다.
```

2023-05-04 05:28 UTC, hochan222 commented on src/ko/proposal-trailing-function-commas.md
> +CLI의 경우 디스크에서 읽을 단일 파일 이름 인수를 지정하거나 원본 텍스트를 CLI에 pipe<sup>[2][]</sup>할 수 있습니다.
```suggestion
CLI의 경우 디스크에서 읽을 단일 파일 이름 인수를 지정하거나 원본 텍스트를 CLI에 pipe<sup>[2][]</sup>로 연결할 수 있습니다.
```

2023-05-05 15:14 UTC, huckjoo commented on src/ko/asynchronous-iterators.md
> +- 호출되면, 비동기 제너레이터 함수는 객체를 반환합니다. (`next`, `throw`, 그리고 `return`) 메서드를 가진 비동기 제너레이터는 `{value, done}`을 직접적으로 반환하는 대신, `{value, done}`을 위한 promise를 반환합니다. 이것은 반환된 비동기 제너레이터 객체를 비동기 반복자로 자동으로 만들어줍니다.
프로미스로 수정하도록 하겠습니다

2023-05-05 15:20 UTC, huckjoo commented on src/ko/asynchronous-iterators.md
> +반복자(iterator) 인터페이스(ECMAScript 2015에 소개된)는 일반적이고 구성 가능한 data consumers와 transformers의 개발을 가능하게 하는 연속적인 데이터 접근 프로토콜입니다.<sup>[1][]</sup> 기본 인터페이스는 `{value, done}` 튜플을 반환하는 `next()` 메서드입니다. 여기서 `done`은
introduce에 도입하다의 의미가 있군요 👍

2023-05-05 15:31 UTC, huckjoo commented on src/ko/asynchronous-iterators.md
> +시퀀스에 있는 다음 value와 데이터 소스의 “done” 상태는 반복자의 메서드가 반환될 때 이미 알고 있어야 하기 때문에, 반복자는 ‘동기적인’ 데이터 소스를 나타내는데에만 적합합니다. JavaScript 프로그래머가 마주하는 많은 데이터 소스(in-memory 배열이나 다른 자료구조와 같은)는 동기화되어 있지만, 다른 많은 데이터 소스는 동기화되어
다시 한번 살펴보니까 제가 '값' 대신 'value'라고 놔둔 이유가
`const { value, done } = syncIterator.next();` 여기에서의 value를 지칭한다고 생각했기 때문인데요, 값이라고 번역해버리면 value를 지칭한다는 의미가 없어져버려서 value라고 놔뒀었네요. 
저는 그래서 value로 놔두는게 좋을 것 같은데 추가 의견 부탁드려요

must는 저도 동의합니다 추가할게요!

2023-05-05 23:09 UTC, hochan222 commented on src/ko/asynchronous-iterators.md
> +시퀀스에 있는 다음 value와 데이터 소스의 “done” 상태는 반복자의 메서드가 반환될 때 이미 알고 있어야 하기 때문에, 반복자는 ‘동기적인’ 데이터 소스를 나타내는데에만 적합합니다. JavaScript 프로그래머가 마주하는 많은 데이터 소스(in-memory 배열이나 다른 자료구조와 같은)는 동기화되어 있지만, 다른 많은 데이터 소스는 동기화되어
넵넵 동의합니다~! 👍👍

2023-05-05 23:09 UTC, hochan222 approved these changes
LGTM :)

2023-05-06 07:09 UTC, merged