[찬우] globalThis 번역
11st-corp/tc39-ko pull request #32
Opened 2023-05-17 16:47 UTC by chanuuuuu

2023-06-07 15:50 UTC, damilog approved these changes
LGTM~! 고생 많으셨ㅅ브니다. 맥락상 눈에 띄는 부분에 대해 리뷰드렸습니다! 
PR에 변경된 커밋이 상당이 많군용..[이 PR](https://github.com/11st-corp/tc39-ko/pull/27#issuecomment-1581020900)에 코멘트 드렸는데 혹 해결이 불가하면 말씀주세요!

2023-06-07 15:50 UTC, damilog commented on src/ko/proposal-global.md
> +이러한 구분은 아래의 `parent.html`, `frame-a.html`,  `frame-b.html`,파일들로 구성된 시나리오에서 확인할 수 있습니다.
```suggestion
이러한 구분은 아래의 `parent.html`, `frame-a.html`, `frame-b.html` 파일들로 구성된 시나리오에서 확인할 수 있습니다.
```

2023-06-07 15:50 UTC, damilog commented on src/ko/proposal-global.md
> +아래의 코드는  `frame-a.html` 입니다.
```suggestion
아래의 코드는 `frame-a.html` 입니다.
```

2023-06-07 15:50 UTC, damilog commented on src/ko/proposal-global.md
> + globalThis.foo = 'a'; globalThis.getGlobalThis = () => globalThis;</script>
```suggestion
 globalThis.foo = 'a'; 
 globalThis.getGlobalThis = () => globalThis;
 </script>  
```

2023-06-07 15:50 UTC, damilog commented on src/ko/proposal-global.md
> + globalThis.getGlobalThis = () => globalThis;</script>
```suggestion
 globalThis.getGlobalThis = () => globalThis;
 </script>  
```

2023-06-07 15:50 UTC, damilog commented on src/ko/proposal-global.md
> +[이 데모](https://bead-pancake.glitch.me/)는 실제 전역객체 내에 네비게이션 동안 변경된 전역변수 `foo`가 저장되어있는 것을 보여줍니다. 하지만 `globalThis`는 네비게이션 동안 변경되지 않았습니다. 그러므로 `globalThis`는 전역객체가 아닙니다.
```suggestion
[이 데모](https://bead-pancake.glitch.me/)는 실제 전역객체 내에 탐색 중에 변경된 전역변수 `foo`가 저장되어있는 것을 보여줍니다. 하지만 `globalThis`는 탐색 중에 변경되지 않았습니다. 그러므로 `globalThis`는 전역객체가 아닙니다.
```

네비게이션을 탐색으로 번역하는 건 어떨까요?

2023-06-07 15:50 UTC, damilog commented on src/ko/proposal-global.md
> +ES6/ES2015는 `Window`/`WindowProxy` 구조를 설명하지 않으며, 단순히 "전역객체"라고 말하고 있습니다. 이 명세는 동일합니다. 만약 ECMAScript에서 top-level `this`가 `WindowProxy`로 설명되도록 명세가 변경된다면, 이러한 변경점은 해당 제안서에도 동일하게 반영되어야합니다.
```suggestion
ES6/ES2015는 `Window`/`WindowProxy` 구조를 설명하지 않으며, 단순히 "전역객체"라고 말하고 있습니다. 이 명세는 동일합니다. 만약 ECMAScript에서 top-level `this`가 `WindowProxy`로 설명되도록 명세가 변경된다면, 이러한 변경점은 해당 제안서에도 동일하게 반영되어야 합니다.
```

2023-06-07 15:50 UTC, damilog commented on src/ko/proposal-global.md
> +For Secure ECMAScript, it is important that all references to the global object be spoof-able and capable of being locked down, so that each context gets its own shadow global context. Additionally,
```suggestion
```
미 삭제된 원문이군요!

2023-06-07 16:00 UTC, huckjoo approved these changes
고생하셨습니다~ LGTM

2023-06-08 07:01 UTC, hochan222 requested changes
고생 많으셨습니다!! 

몇가지 리뷰사항 남겨두었습니다 :)

2023-06-08 07:01 UTC, hochan222 commented on src/ko/proposal-global.md
> +Secure ECMAScript에서는 전역객체에 대한 모든 참조가 스푸닝 가능하며, 잠길 수 있기 때문에 각 컨테스트가 숨겨진 전역 컨텍스트를 가질 수 있도록 하는 것이 중요합니다. 추가적으로, 전역객체에 대한 참조는 SES가 단순히 재귀적으로 동결하기를 원하는 다른 ECMAScript의 독립된 객체들에서 접근이 불가능해야합니다. 이 제안서에서 `glob
```suggestion
Secure ECMAScript에서는 전역 객체에 대한 모든 참조가 스푸닝 가능하며, 잠길 수 있기 때문에 각 컨테스트가 숨겨진 전역 컨텍스트를 가질 수 있도록 하는 것이 중요합니다. 추가적으로, 전역 객체에 대한 참조는 SES가 단순히 재귀적으로 동결하기를 원하는 다른 ECMAScript의 내제 객체에서 접근이 불가능해야합니다. 이 제안서에서 `globalThis`는 전역 객체의 쓰기 및 구성 가능한 속성이므로, SES의 요구 사항을 충족해야 합니다.
```

2023-06-08 07:01 UTC, hochan222 commented on src/ko/proposal-global.md
> +~~`System.global` 대신 기존 글로벌 속성 이름, 특히 `global` 또는 `window` 중 하나를 다시 정의하고자 하였습니다. 이 두 가지 중 하나가 런타임 환경 탐지를 수행하는 기존 코드를 중단하는지에 대한 추가 연구가 수행될 것입니다. 추가 연구를 통해 `global`을 사용해도 기존 코드가 깨지지 않을 것으로 확인되었습니다.~~
```suggestion
~~`System.global` 대신 기존 전역 속성 이름, 특히 `global` 또는 `window` 중 하나를 다시 정의하고자 하였습니다. 이 두 가지 중 하나가 런타임 환경 탐지를 수행하는 기존 코드를 중단하는지에 대한 추가 연구가 수행될 것입니다. 추가 연구를 통해 `global`을 사용해도 기존 코드가 깨지지 않을 것으로 확인되었습니다.~~
```

2023-06-21 15:21 UTC, merged