[다미] proposal-exponentiation-operator
11st-corp/tc39-ko pull request #4
Opened 2023-03-15 15:22 UTC by damilog

proposal-exponentiation-operator  추가하였습니다.

### 궁금한 점
@hochan222 님께 몇 가지 궁금한 사항이 있는데요.

1. 용어집에 제목을 정리하는 표에는 h1~h3로 작성된 단어를 모두 포함시키면 될까요? h1 (가장 큰 제목) 만 포함시키는 것인지 궁금합니다.
2. 제목 중 Render Spec 을 번역할 때 render의 의미를 명확히 표현하는 단어가 떠오르지 않아 '명세서 렌더링' 이라고 작성을 하였는데요. 이렇게 한국어와 기술 용어를 혼용하는 예외 사항을 두어도 괜찮을지, 혹 혼동을 주는 건 아닐 지 고민이 됩니다.
3. Implementation Progress을 '구현 진행' 으로 번역했는데 어색하게 느껴집니다. 적절한 대체어가 있을까요??

2023-03-15 16:00 UTC, hochan222 requested changes
고생 많으셨습니다~! 몇가지 리뷰 사항 남겨두었습니다 :)

2023-03-15 16:00 UTC, hochan222 commented on glossary.md
> +| element                      | 요소           |           |
```suggestion
| 용어 | 번역 | 참고 링크 |
| --- | --- | --- |
| Abstract Equality Comparison | 추상 동등 비교 | |
| element | 요소 | |
```

markdown table 문법의 경우 현재 변경주신대로 관리하다보면... 추후 유지보수가 어려움을 많이 느꼈습니다. 예를들어.. 번역 영역의 길이가 길어지거나 짧아진다면 모든 요소들의 공백을 추가해야하고 `-`도 추가해야합니다. 

또, 내용의 길이가 길어지면 개개인이 설정한 IDE 마다 table 문법이 보이는것에 차이가 있어서 차라리 가장 최소로 유지하는건 어떨까 조그마한 의견 내봅니다.

2023-03-15 16:00 UTC, hochan222 commented on src/ko/proposal-exponentiation-operator.md
> +
```suggestion

[명세서](https://tc39.es/ecma262/#sec-exp-operator)

```

누락 되어서 추가했습니다.

2023-03-15 16:00 UTC, hochan222 commented on src/ko/proposal-exponentiation-operator.md
> +### 4단계
```suggestion
### 4 단계
```

2023-03-15 16:00 UTC, hochan222 commented on src/ko/proposal-exponentiation-operator.md
> +구현 진행
```suggestion
구현 진행률
```

혹은 구현 진행 단계 어떤가요..?

2023-03-15 16:00 UTC, hochan222 commented on src/ko/proposal-exponentiation-operator.md
> +## 정보를 주는
ㅋㅋㅋㅋ 그동안 이런 케이스는 경험한적이 없었어서 애매하네요 음..

2023-03-15 16:00 UTC, hochan222 commented on src/ko/proposal-exponentiation-operator.md
> +- [중위 표기법](https://ko.wikipedia.org/wiki/%EC%A4%91%EC%9C%84_%ED%91%9C%EA%B8%B0%EB%B2%95)은 함수 표기법보다 간결하므로 더 선호됩니다.
```suggestion
- [중위 표기법](https://en.wikipedia.org/wiki/Infix_notation)은 함수 표기법보다 간결하므로 더 선호됩니다.
```

한글 wiki가 영문 wiki 보다 미흡한 경우가 많아서 영문 wiki로 링크 거는것이 좋아 보이는데 의견 부탁드립니다.

2023-03-15 16:00 UTC, hochan222 commented on src/ko/proposal-exponentiation-operator.md
> +### 명세서 렌더링
```suggestion
### 렌더 명세
```

2023-03-16 08:04 UTC, damilog commented on glossary.md
> +| element                      | 요소           |           |
저장할때 prettier extension이 작동했었나보네요 좋은 의견이라 생각합니다!

2023-03-16 08:04 UTC, damilog commented on src/ko/proposal-exponentiation-operator.md
> +### 4단계
오 띄어쓰기를 해줘야하는 군요!

2023-03-16 08:04 UTC, damilog commented on src/ko/proposal-exponentiation-operator.md
> +구현 진행
진행 단계 좋습니다!!

2023-03-16 08:05 UTC, damilog commented on src/ko/proposal-exponentiation-operator.md
> +## 정보를 주는
ㅋㅋㅋㅋ뭔가 번역된 문서에서 보단 어투가 맞는거 같기도해서ㅋㅋㅋ 일단 냅두겠습니다

2023-03-16 08:06 UTC, damilog commented on src/ko/proposal-exponentiation-operator.md
> +- [중위 표기법](https://ko.wikipedia.org/wiki/%EC%A4%91%EC%9C%84_%ED%91%9C%EA%B8%B0%EB%B2%95)은 함수 표기법보다 간결하므로 더 선호됩니다.
번역본이라 한글 위키로 걸어보았는데 내용 차이가 있을 수 있군요 번역이 안되어있는 위키도 있을 수 있으니 영문 위키로 달아놓는게 좋겠네요.

2023-03-16 08:07 UTC, damilog commented on src/ko/proposal-exponentiation-operator.md
> +### 명세서 렌더링
제가 고민했던 부분이 이건데요, 렌더 명세 처럼 영어를 그대로 쓰는 것이라면 명세서 렌더링도 괜찮지 않을까요??

2023-03-17 09:27 UTC, huckjoo commented on src/ko/proposal-exponentiation-operator.md
> +## 정보를 주는
'정보를 주는'도 괜찮은것 같아요 ㅋㅋㅋ
아니면 아예 '정보 제공' 으로 형용사를 명사로 바꿔버려도 의미가 전달되지 않을까 싶습니다.

2023-03-20 16:33 UTC, hochan222 commented on src/ko/proposal-exponentiation-operator.md
> +### 명세서 렌더링
네 좋습니다~

2023-03-28 12:45 UTC, merged