string-pad-start-end 번역 리뷰
11st-corp/tc39-ko pull request #9
Opened 2023-03-17 09:11 UTC by huckjoo

2023-03-17 09:18 UTC, huckjoo reviewed
pad 리뷰 남겨두었습니다. @hochan222 님 리뷰에 대한 리뷰 부탁드려요~

2023-03-17 09:18 UTC, huckjoo commented on src/ko/proposal-string-pad-start-end.md
> +[#6](https://github.com/tc39/proposal-string-pad-start-end/issues/6)에 따라, "left" 및 "right" 기능을 모두 제공하는 다중 문자 채우기 문자열을 지원하는 유일한 언어는 Ruby와 PHP입니다. 두 언어의 "왼쪽 패드"는 마지막이 아닌 채우기 문자열의 _첫_ 부분을 차지합니다. 이것이 중요한
이런 이탤릭체도 번역하는게 어떤지 의견을 구합니다~

2023-03-17 09:18 UTC, huckjoo commented on src/ko/proposal-string-pad-start-end.md
>  ## 채우기 문자열과 관련된 왼쪽 패딩: 다른 언어와의 일관성
```suggestion
## 문자열을 채우는 것과 관련된 왼쪽 패딩: 다른 언어와의 일관성
```
이렇게 바꾸는 것은 어떤가요? 채우기 문자열이란게 무엇인지 잘 와닿지 않는 것 같습니다.

2023-03-17 09:18 UTC, huckjoo commented on src/ko/proposal-string-pad-start-end.md
> +[#6](https://github.com/tc39/proposal-string-pad-start-end/issues/6)에 따라, "left" 및 "right" 기능을 모두 제공하는 다중 문자 채우기 문자열을 지원하는 유일한 언어는 Ruby와 PHP입니다. 두 언어의 "왼쪽 패드"는 마지막이 아닌 채우기 문자열의 _첫_ 부분을 차지합니다. 이것이 중요한
```suggestion
[#6](https://github.com/tc39/proposal-string-pad-start-end/issues/6)에 따라, "왼쪽" 및 "오른쪽" 기능을 모두 제공하는 다중 문자 채우기 문자열을 지원하는 유일한 언어는 Ruby와 PHP입니다. 두 언어의 "왼쪽 패드"는 마지막이 아닌 채우기 문자열의 _첫_ 부분을 차지합니다. 이것이 중요한 이유에 대한 분명한 예는 `"abc".padStart(10, "0123456789")`가 채우기 문자열의 마지막 부분을 취하면 `"3456789abc"`가 되고 첫 부분을 취하면 `"0123456abc"`가 되는 것입니다. 즉, `string.padStart(mask.length, mask)`는 예상대로 작동해야 합니다.
```

위의 "max length"는 "최대 길이"로 번역하였는데, 여기는 "left"와 "right"로 그대로 두신 이유가 있을까요??

2023-03-17 09:18 UTC, huckjoo commented on src/ko/proposal-string-pad-start-end.md
> +명세서를 [마크다운 형식](https://github.com/tc39/proposal-string-pad-start-end/blob/main/spec.md)으로 보거나 [HTML](http://tc39.github.io/proposal-string-pad-start-end/)로 렌더링할 수 있습니다.
링크 클릭시 404가 떠서 추가하였습니다.

2023-03-17 09:22 UTC, huckjoo commented on src/ko/proposal-string-pad-start-end.md
> +2015년 11월 TC39 회의에 따른 개정: 이름은 `padStart`/`padEnd`이고 `trimLeft`/`trimRight`는 `trimStart`/`trimEnd`로 변경되며, `trimLeft`/`trimRight` 별칭은 웹 호환성을 위해 부록 B에 추가됩니다.
이건 for의 해석에 따라 달라지는 것인데 웹 호환성을 "위해서" 부록 B에 추가되었다고 생각해서 변경해보았습니다.
이 부분은 그렇게 큰 차이는 없는것도 같아서 반영하지 않으셔도 될 것 같아요 ㅋㅋ

2023-03-20 16:12 UTC, hochan222 commented on src/ko/proposal-string-pad-start-end.md
>  ## 채우기 문자열과 관련된 왼쪽 패딩: 다른 언어와의 일관성
`the fill string`은 아래 명세서 내용 중에서 2번째 인자를 뜻하는 명사합니다. 저도 고민을 많이했는데, '채워질 문자열'로 타협보았습니다. 의견 부탁드려요 :)
 
summary는 '채워질 문자열'로 번역을 했는데 여기는 아직 반영을 안했네요! 꼼꼼한 확인 감사합니다.

<img width="964" alt="image" src="https://user-images.githubusercontent.com/22424891/226400173-6dc1f82a-75d3-48be-af1f-927d1b99fcb6.png">

2023-03-20 16:21 UTC, hochan222 commented on src/ko/proposal-string-pad-start-end.md
> +[#6](https://github.com/tc39/proposal-string-pad-start-end/issues/6)에 따라, "left" 및 "right" 기능을 모두 제공하는 다중 문자 채우기 문자열을 지원하는 유일한 언어는 Ruby와 PHP입니다. 두 언어의 "왼쪽 패드"는 마지막이 아닌 채우기 문자열의 _첫_ 부분을 차지합니다. 이것이 중요한
rjust, ljust나 이슈에서 쓰인 padRight, padLeft와의 연관성 및 가독성을 위해 그대로 두었는데, 지금 다시 고민해보니 번역하는것이 좋아보이네요! 

https://github.com/11st-corp/tc39-ko/pull/9/commits/339ac6a1af0b8f24308db3463afd336680cfc67b 반영했습니다 :)

2023-03-20 16:23 UTC, hochan222 commented on src/ko/proposal-string-pad-start-end.md
> +명세서를 [마크다운 형식](https://github.com/tc39/proposal-string-pad-start-end/blob/main/spec.md)으로 보거나 [HTML](http://tc39.github.io/proposal-string-pad-start-end/)로 렌더링할 수 있습니다.
감사합니다 :)

2023-03-20 16:25 UTC, hochan222 commented on src/ko/proposal-string-pad-start-end.md
>  ## 채우기 문자열과 관련된 왼쪽 패딩: 다른 언어와의 일관성
- https://github.com/11st-corp/tc39-ko/pull/9/commits/631e42e13150c1042dad65aa38611ce5edd8e3c2

2023-03-20 16:26 UTC, hochan222 commented on src/ko/proposal-string-pad-start-end.md
> +2015년 11월 TC39 회의에 따른 개정: 이름은 `padStart`/`padEnd`이고 `trimLeft`/`trimRight`는 `trimStart`/`trimEnd`로 변경되며, `trimLeft`/`trimRight` 별칭은 웹 호환성을 위해 부록 B에 추가됩니다.
아뇨 너무 좋은 리뷰입니다. 동의합니다~ 위해 좋습니다~!

2023-03-20 16:27 UTC, hochan222 requested changes
@huckjoo 님 안녕하세요 :)

꼼꼼히 봐주셔서 감사합니다!

리뷰사항 반영 및 코멘트 드렸습니다. 확인 후 의견 부탁드립니다 :)

2023-03-21 23:42 UTC, huckjoo commented on src/ko/proposal-string-pad-start-end.md
> +[#6](https://github.com/tc39/proposal-string-pad-start-end/issues/6)에 따라, "left" 및 "right" 기능을 모두 제공하는 다중 문자 채우기 문자열을 지원하는 유일한 언어는 Ruby와 PHP입니다. 두 언어의 "왼쪽 패드"는 마지막이 아닌 채우기 문자열의 _첫_ 부분을 차지합니다. 이것이 중요한
mdn 번역 안내서도 있군요~ 내용 잘 봤습니다. '첫' 으로 번역하는거 좋아요 👍

2023-03-21 23:44 UTC, huckjoo commented on src/ko/proposal-string-pad-start-end.md
>  ## 채우기 문자열과 관련된 왼쪽 패딩: 다른 언어와의 일관성
'채우기 문자열'보다는 '채워질 문자열'이 더 이해하기 쉽네요. 좋습니다!

2023-03-29 14:36 UTC, hochan222 commented on src/ko/proposal-string-pad-start-end.md
> +[#6](https://github.com/tc39/proposal-string-pad-start-end/issues/6)에 따라, "left" 및 "right" 기능을 모두 제공하는 다중 문자 채우기 문자열을 지원하는 유일한 언어는 Ruby와 PHP입니다. 두 언어의 "왼쪽 패드"는 마지막이 아닌 채우기 문자열의 _첫_ 부분을 차지합니다. 이것이 중요한
반영했습니다!

- https://github.com/11st-corp/tc39-ko/pull/9/commits/1b4cf6754a56b15b7cb813a8cbc3034f2be7b1d4

2023-03-29 14:37 UTC, hochan222 approved these changes
LGTM :)

2023-03-29 14:37 UTC, merged